npx hardhat run examples/cube3D_GZIP_BASE64/deploy.js --network $npm_config_network
npx hardhat run examples/cube3D_GZIP_URLSafe/deploy.js --network $npm_config_network
npx hardhat run examples/cube3D_PNG_URLSafe/deploy.js --network $npm_config_network
npx hardhat run examples/cube3D_PNG_URLSafe_CustomWrap/deploy.js --network $npm_config_network
npx hardhat run examples/ethfs_p5/deploy.js --network $npm_config_network
npx hardhat run examples/ethfs_p5_URLSafe/deploy.js --network $npm_config_network
npx hardhat run examples/randomShapes/deploy.js --network $npm_config_network
npx hardhat run examples/stacked3DObjects/deploy.js --network $npm_config_network
npx hardhat run examples/threeJSModules_URLSafe/deploy.js --network $npm_config_network